.github/auto_assign.yml

Added Auto Assign

---

api/src/models/language.js

Made requested updates to certain fields in Language schema models based on product/design changes.
Fixes #83

Fix language schema

---

client/.expo/packager-info.json
client/src/theme/colors.js

Updated Client Theme - Added Bright 7000 Languages Red Color

---

api/src/models/language.js

Added new fields to CourseDetails

Updated CourseDetails schema

---

api/src/models/language.js

Made some fields not required in CourseDetails schema

switched to required false

---

client/.expo/packager-info.json
client/src/components/HomeBaseCase/HomeBaseCase.js
client/src/navigator/Navigator.js
client/src/pages/Home/Home.js
client/src/pages/Landing/Landing.js
client/src/redux/slices/auth.slice.js

Fixed Bug with Redux and Admin ID Token

---

api/src/api/user.js
api/src/utils/constants.js
api/src/utils/languageHelper.js
api/src/utils/userHelper.js
api/test/db-data/courses.json
api/test/db-data/users.json
api/test/mock-data/user-mock-data.js
api/test/routes/course.test.js
api/test/routes/user.test.js
api/test/utils/auth.js

🚀 
Fetches a user's data and the languages they belong to given a user ID Token.
- Created `GET '/user/'`
- Wrote some helper methods that can be used in future code
- Wrote a test
Fixes #87 
- Maybe add a few more tests?

Created Endpoint for Getting User Data

---

client/src/components/HomeBaseCase/HomeBaseCase.js
client/src/pages/Home/Home.js
client/src/redux/slices/auth.slice.js

Fixed Redux Logout Action

---

api/src/api/language/course.js
api/src/api/language/index.js
api/src/api/language/lesson.js
api/src/api/language/unit.js
api/src/api/language/vocab.js
api/src/api/user.js

Restructured API Routes

---

api/src/api/language/course.js
api/src/api/language/lesson.js
api/src/api/language/vocab.js
api/src/utils/constants.js
api/src/utils/languageHelper.js
api/test/mock-data/lesson-mock-data.js
api/test/routes/course.test.js
api/test/routes/lesson.test.js
api/test/routes/vocab.test.js

🚀 
Created POST '/lesson' for creating a new lesson with 0 vocab items.
Fixes #<number>

Created POST '/lesson'

---

api/src/api/language/lesson.js
api/src/api/language/vocab.js
api/src/models/index.js
api/src/models/language.js
api/src/utils/languageHelper.js
api/test/mock-data/lesson-mock-data.js
api/test/mock-data/vocab-mock-data.js
api/test/routes/course.test.js
api/test/routes/lesson.test.js
api/test/routes/user.test.js

🚀 
- Wrote an endpoint for making changes to more than one lesson at once. This will be useful for the Manage Units/Lessons page, where we unselect/select and re-order lessons and units.
- Wrote Mongoose validation that checks if a lesson has a unique `_order` before saving.
- Remove unnecessary code from previously created endpoints and updated their accompanying tests.
Fixes #81

Created PUT '/lesson'

---

api/src/utils/aws/exports.js
api/src/utils/aws/s3.js
api/test.env
package.json
yarn.lock

Added Setup AWS S3 Code

---

api/src/api/language/lesson.js
api/src/api/language/unit.js
api/src/utils/languageHelper.js
api/test/mock-data/unit-mock-data.js
api/test/routes/course.test.js
api/test/routes/unit.test.js

🚀 
Created endpoint for re-ordering and selecting/unselecting units. It is the same code as `PUT '/lesson.'`

Created PUT '/unit' endpoint

---

client/src/navigator/Drawer/Drawer.js
client/src/theme/nativebase.js

Fixed Navigator + NativeBase Bug 

---

api/src/api/language/lesson.js
api/src/api/language/unit.js
api/src/api/language/vocab.js
api/test/db-data/courses.json
api/test/db-data/users.json
api/test/mock-data/user-mock-data.js
api/test/routes/lesson.test.js
api/test/routes/unit.test.js
client/.expo/packager-info.json
client/src/api/api.js
client/src/redux/slices/language.slice.js

Added Client API request code and fields to Language Slice

---

api/src/api/language/unit.js
api/test/mock-data/unit-mock-data.js
api/test/routes/unit.test.js

Unit Post Endpoint

---

api/src/api/language/image.js
api/src/api/language/index.js

Created GET '/image'

---

client/app.config.js

Update iosClientId and androidClientId

---

api/src/api/language/unit.js
client/.expo/packager-info.json

🚀 
POST 'language/unit' got `courseId` from `req.body `by getting `_course_id`, but it should have been `course_id`. 
Fixes #<number>

Hotfix: Fixed POST 'language/unit' bug

---

api/src/api/language/unit.js
client/.expo/packager-info.json
client/app.config.js
client/src/pages/CreateUnit/CreateUnit.js

Hotfix v2: Fixed POST 'language/unit' bug 

---

client/src/pages/Landing/Landing.js

Change the logo to be aligned with the top of the screen instead of the bottom, fixing the issue on different screen sizes. Fixes #180.

Change logo alignment

---

client/src/components/StyledCard/StyledCard.js

Restyles the StyledCard to match new figma design. Works on both mobile and tablet. 
Fixes #232.

Redesign Audio Icon on the StyledCard

---

client/src/pages/Apply/Apply.js

Pushes in the permission disclaimer and aligns the text from the button checkbox on the new contributor page.
Fixes #228.

UI Fix on Apply to Contribute

---

README.md

Update README.md with Fall 2022 Team

---

.gitignore
client/.expo/packager-info.json
client/.expo/settings.json
client/.gitignore
client/src/navigator/Drawer/Drawer.js

Removed "Loading..." text for the user's name on the Drawer Navigator (s\o @rustom)
Fixes #260

Removed "Loading..." text on the Drawer Navigator

---

client/app.config.js
client/src/api/axios-config.js

:rocket: Ready
Elegant solution to make sure the auth refreshes only once

Make sure auth only tries to refresh once

---

client/app.config.js

Switch Expo Client ID to Dev IDS

---

api/README.md
client/app.config.js
client/src/pages/Landing/Landing.js

Remove iOS and Android Client IDs Reference

---

client/.expo/settings.json
client/app.config.js
client/src/components/Drawer/Drawer.js
client/src/components/DrawerLogoutButton/DrawerLogoutButton.js
client/src/components/LanguageHome/LanguageHome.js
client/src/components/ManageView/ManageView.js
client/src/components/RecordAudioView/RecordAudioView.js
client/src/components/RequiredField/RequiredField.js
client/src/navigator/Drawer/Drawer.js
client/src/navigator/Navigator.js
client/src/navigator/Stacks/Stacks.js
client/src/navigator/Tabs/Tabs.js
client/src/pages/Intro/Intro.js
client/src/pages/Landing/Landing.js
client/src/pages/LessonHome/LessonHome.js
client/src/pages/SelectLanguage/SelectLanguage.js
client/src/pages/VocabDrawer/VocabDrawer.js
client/src/theme/colors.js

🚀 
Bugs resolved:
- On the Drawer, Courses with 1 Unit only displayed "Unit". Made sure it displays "1 Unit" now.
- Made sure to display a pencil icon for the StyledCards on the CourseLesson page.
These bugs most likely occurred because of a past merge conflict.

Resolved Drawer and StyledCard UI Bugs 

---

client/.expo/settings.json
client/src/api/axios-config.js
client/src/components/DrawerLogoutButton/DrawerLogoutButton.js
client/src/components/HomeBaseCase/HomeBaseCase.js
client/src/components/LanguageHome/LanguageHome.js
client/src/components/ManageView/ManageView.js
client/src/components/RecordAudioView/RecordAudioView.js
client/src/navigator/Navigator.js
client/src/pages/VocabDrawer/VocabDrawer.js
client/src/redux/slices/auth.slice.js
client/src/theme/nativebase.js
client/src/utils/auth.js
client/src/utils/constants.js

:rocket: Ready
1. Removed client id from secure storage
2. Added client secret to part of refresh auth call, weird how now it requires client secret where as previously it didn't(may have to do with new clientId?)
3. Moved delete tokens inside logout reducer
4. Added idToken check in reducer(see if it exists)

Added client secret to refresh auth and minor tweaks

---

client/src/components/LanguageHome/LanguageHome.js
client/src/components/LearnerHome/LearnerHome.js
client/src/navigator/Tabs/Tabs.js
client/src/pages/Activity1/Activity1.js
client/src/pages/Activity2/Activity2.js
client/src/pages/StartActivity/StartActivity.js
client/src/utils/i18n/translations.js

🚀 
Resolved inconsistencies between our Figma designs and app:
- Proper positioning of feedback text on the Activity pages
- Proper numbering of activities
- Make entire card components clickable on the Learner Flow pages
- Change font size of feedback text on the Activity pages.
- Make header text on the Language and Learner Home pages smaller.
- Add French translations on the `<StartActivity/>` page.

Resolve UI Inconsistencies

---

client/.expo/packager-info.json
client/.expo/settings.json
client/app.config.js
client/src/api/api.js
client/src/api/axios-config.js
client/src/navigator/Navigator.js
client/src/pages/StartActivity/StartActivity.js
client/src/utils/auth.js
client/src/utils/languageHelper.js

🚀 
Found a bug where signing into the release (expo publish) app crashes the app because of conflicting idTokens and refreshTokens.
Fixes #<number>

Add Check for Failed getUser() Response

---

client/.expo/packager-info.json
client/src/api/api.js
client/src/api/axios-config.js
client/src/components/HomeBaseCase/HomeBaseCase.js
client/src/pages/StartActivity/StartActivity.js
client/src/utils/auth.js
client/src/utils/languageHelper.js

Added Search Navigation to HomeBaseCase
